ShoppingChart/Models/ErrorViewModel.cs
using System;

namespace ShoppingChart.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ShoppingChart/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShoppingChart.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingChart.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShoppingChart/Controllers/ProductDetailController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingChart.Business.Abstract;
using ShoppingChart.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingChart.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly ShoppingChartContext _context;
        private IProductDetailService _productDetailService;

        public ProductDetailController(ShoppingChartContext context, IProductDetailService productDetailService)
        {
            _context = context;
            _productDetailService = productDetailService;
        }
        public IActionResult Index()
        {
            var response = _productDetailService.GetAllProductDetail();
            return View(response);
        }

        [HttpPost]
        public ActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewProduct(ProductDetail productDetail)
        {
            _productDetailService.CreateProductDetail(productDetail);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _productDetailService.DeleteProductDetail(Id);
            return RedirectToAction("Index");
        }

        public ActionResult UpdateProduct(int Id)
        {
            var productDetail = _context.ProductDetail.Find(Id);
            _productDetailService.UpdateProductDetail(productDetail);
            return View("UpdateProduct");
        }

        public ActionResult Update(ProductDetail productDetail)
        {
            _productDetailService.UpdateProductDetail(productDetail);
            return RedirectToAction("Index");
        }
    }
}

ShoppingChart/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using ShoppingChart.Business.Abstract;
using ShoppingChart.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingChart.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ShoppingChartContext _context;
        private IProductService _productService;

        public ProductsController(ShoppingChartContext context, IProductService productService)
        {
            _context = context;
            _productService = productService;
        }
        public IActionResult Index()
        {
            var response = _productService.GetAllProduct();
            return View(response);
        }

        [HttpGet]
        public ActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewProduct(Products products)
        {
            _productService.CreateProducts(products);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            _productService.DeleteProducts(Id);
            return RedirectToAction("Index");
        }

        public ActionResult UpdateProduct(int Id)
        {
            var product = _context.Products.Find(Id);
            _productService.UpdateProducts(product);
            return View("UpdateProduct", product);
        }

        public ActionResult Update(Products products)
        {
            _productService.UpdateProducts(products);
            return RedirectToAction("Index");
        }
    }
}

ShoppingChart/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShoppingChart/Views/ProductDetail/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h4>Product Detail</h4>

ShoppingChart/Views/Products/CreateProduct.cshtml
@model ShoppingChart.Entities.Products

<div>
    <form action="NewProduct" method="post">

        <div class="box-body">
            <div class="form-group>
                <label class="col-sm-2 control-label">Product Name</label>
                <div class="col-sm-10">
                    @Html.TextBoxFor(m => m.ProductName, new { @class = "form-control", required = "required", autocomplete = "off" })
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-info pull-right">Create</button>
    </form>
</div>

ShoppingChart/Views/Products/Index.cshtml
@model IEnumerable<ShoppingChart.Entities.Products>

<div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Id</td>
                <td>Product Name</td>
                <td>Edit</td>
                <td>Delete</td>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(p => item.Id)</td>
                    <td>@Html.DisplayFor(p => item.ProductName)</td>
                    <td><a class="btn btn-success" href="/Products/UpdateProduct/@item.Id">Edit</a></td>
                    <td><a class="btn btn-danger" href="/Products/Delete/@item.Id">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>

    <a class="btn bg-warning" href="~/Products/CreateProduct">Create Product</a>
</div>

ShoppingChart/Views/Products/UpdateProduct.cshtml
@model ShoppingChart.Entities.Products

<div>
    <form class="form-horizontal" action="/Products/Update" method="post">
        <div class="box-body">
            <div class="form-group>
                <label class="col-sm-2 control-label">Product Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="ProductName" value="@Model.ProductName" autocomplete="off" required="required" maxlength="50" />
                </div>
            </div>
            <input type="hidden" name="Id" value="@Model.Id" />

        </div>
        <div class="box-footer">
            <div class="pull-right">
                <a href="~/Products/Index" class="btn btn-danger">Cancel</a>
                <button type="submit" class="btn btn-info pull-right">Update</button>
            </div>
        </div>
    </form>
</div>

ShoppingChart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingChart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingChart</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductDetail" asp-action="Index">Product Detail</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ShoppingChart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>